services:
  android-emulator:
    container_name: android-emulator
    image: budtmo/docker-android:emulator_11.0
    privileged: true
    ports:
      - 6080:6080
      - 5554:5554
      - 5555:5555
    environment:
      DEVICE: "pixel"
      WEB_VNC: "true"
      APPIUM: "false"
      EMULATOR_TIMEOUT: "900"
      RELAXED_SECURITY: "true"
      EMULATOR_ARGS: "-gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim"
    shm_size: '4gb'
    healthcheck:
      test: ["CMD-SHELL", "adb devices | grep -q 'device$'"]
      interval: 10s
      timeout: 5s
      retries: 60
      start_period: 30s
  maestro-runner:
    build: .
    image: steveceto/maestro-runner:latest
    container_name: maestro-tester
    command: /app/run_tests.sh
    environment:
      - APK_URL=https://expo.dev/artifacts/eas/pNjGzRbdX8ftuNhJFBv3QG.apk
    volumes:
      - .:/app
      - ./allure-results:/app/allure-results
    depends_on:
      android-emulator:
        condition: service_healthy
      mockserver:
        condition: service_started

  mockserver:
    image: mockserver/mockserver:latest
    container_name: mockserver
    ports:
      - "1080:1080"
    environment:
      MOCKSERVER_LIVENESS_HTTP_GET_PATH: "/mockserver/status"
    volumes:
      - ./mockserver:/config
    command: -proxyPort 1080 -initializationJsonPath /config/initializer.json
